// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace jifas_assistant.DAL.Models;

[Index("CreatedAt", Name = "IX_Chats_CreatedAt")]
[Index("UserId", Name = "IX_Chats_UserId")]
public partial class Chats
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    public string UserId { get; set; }

    [Required]
    public string Message { get; set; }

    public string Response { get; set; }

    public bool? IsOutOfScope { get; set; }

    public double? Confidence { get; set; }

    public string RelatedDocumentIds { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}