// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace jifas_assistant.DAL.Models;

[Index("Category", Name = "IX_KBDocuments_Category")]
[Index("CreatedAt", Name = "IX_KBDocuments_CreatedAt")]
[Index("IsActive", Name = "IX_KBDocuments_IsActive")]
public partial class KnowledgeBaseDocuments
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(500)]
    public string Title { get; set; }

    [Required]
    public string Content { get; set; }

    [StringLength(100)]
    public string Category { get; set; }

    [StringLength(500)]
    public string Tags { get; set; }

    public string FilePath { get; set; }

    public string Embedding { get; set; }

    public int? EmbeddingDimensions { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? ViewCount { get; set; }

    public double? RelevanceScore { get; set; }

    [StringLength(100)]
    public string CreatedBy { get; set; }

    [StringLength(100)]
    public string UpdatedBy { get; set; }

    [InverseProperty("Document")]
    public virtual ICollection<KnowledgeBaseChunks> KnowledgeBaseChunks { get; set; } = new List<KnowledgeBaseChunks>();
}