// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Pgvector;

namespace jifas_assistant.DAL.Models;

[Index("ChunkIndex", Name = "IX_KBChunks_ChunkIndex")]
[Index("DocumentId", Name = "IX_KBChunks_DocumentId")]
public partial class KnowledgeBaseChunks
{
    [Key]
    public int Id { get; set; }

    public int DocumentId { get; set; }

    public int ChunkIndex { get; set; }

    [Required]
    public string Content { get; set; }

    public string Embedding { get; set; }

    [Column(TypeName = "vector(2560)")]
    public Vector EmbeddingVector { get; set; }

    public int? EmbeddingDimensions { get; set; }

    public int? StartCharPos { get; set; }

    public int? EndCharPos { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    [ForeignKey("DocumentId")]
    [InverseProperty("KnowledgeBaseChunks")]
    public virtual KnowledgeBaseDocuments Document { get; set; }
}
