// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace jifas_assistant.DAL.Models;

[Index("CreatedAt", Name = "IX_Metrics_CreatedAt")]
[Index("MetricName", Name = "IX_Metrics_MetricName")]
public partial class Metrics
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(200)]
    public string MetricName { get; set; }

    public double? MetricValue { get; set; }

    [StringLength(100)]
    public string Category { get; set; }

    public DateTime? CreatedAt { get; set; }
}