// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace jifas_assistant.DAL.Models;

[Index("ChatId", Name = "IX_UserFeedbacks_ChatId")]
[Index("CreatedAt", Name = "IX_UserFeedbacks_CreatedAt")]
public partial class UserFeedbacks
{
    [Key]
    public int Id { get; set; }

    public int? ChatId { get; set; }

    [StringLength(100)]
    public string UserId { get; set; }

    public int? Rating { get; set; }

    public string Comment { get; set; }

    public bool? IsHelpful { get; set; }

    public DateTime? CreatedAt { get; set; }
}