CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" varchar(150) NOT NULL PRIMARY KEY,
    "ProductVersion" varchar(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS "KnowledgeBaseDocuments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" varchar(500) NOT NULL,
    "Content" text NOT NULL,
    "Category" varchar(100),
    "Tags" varchar(500),
    "FilePath" text,
    "Embedding" text,
    "EmbeddingDimensions" integer DEFAULT 0,
    "IsActive" boolean DEFAULT true,
    "CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "ViewCount" integer DEFAULT 0,
    "RelevanceScore" double precision DEFAULT 1.0,
    "CreatedBy" varchar(100) DEFAULT 'System',
    "UpdatedBy" varchar(100) DEFAULT 'System'
);

CREATE TABLE IF NOT EXISTS "KnowledgeBaseChunks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DocumentId" integer NOT NULL,
    "ChunkIndex" integer NOT NULL,
    "Content" text NOT NULL,
    "Embedding" text,
    "EmbeddingVector" vector(2560),
    "EmbeddingDimensions" integer DEFAULT 0,
    "StartCharPos" integer,
    "EndCharPos" integer,
    "CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ChatHistory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SessionId" varchar(100) NOT NULL,
    "UserId" varchar(100),
    "UserMessage" text NOT NULL,
    "AiResponse" text NOT NULL,
    "ResponseSource" varchar(100),
    "ConfidenceScore" double precision,
    "IsFromKnowledgeBase" boolean NOT NULL DEFAULT false,
    "ResponseTimeMs" bigint NOT NULL DEFAULT 0,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Success" boolean NOT NULL DEFAULT true,
    "UsedDocumentIds" text
);

CREATE TABLE IF NOT EXISTS "AiUsageLogs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" varchar(200),
    "SessionId" varchar(200),
    "ActiveModule" varchar(100),
    "Model" varchar(100) NOT NULL DEFAULT 'qwen3:8b',
    "CallType" varchar(50),
    "PromptTokens" integer NOT NULL DEFAULT 0,
    "CompletionTokens" integer NOT NULL DEFAULT 0,
    "TotalTokens" integer NOT NULL DEFAULT 0,
    "TotalDurationMs" bigint NOT NULL DEFAULT 0,
    "LoadDurationMs" bigint NOT NULL DEFAULT 0,
    "PromptEvalDurationMs" bigint NOT NULL DEFAULT 0,
    "EvalDurationMs" bigint NOT NULL DEFAULT 0,
    "TokensPerSecond" double precision NOT NULL DEFAULT 0,
    "ResponseLengthChars" integer NOT NULL DEFAULT 0,
    "PromptLengthChars" integer NOT NULL DEFAULT 0,
    "ConfidenceScore" double precision,
    "IsError" boolean NOT NULL DEFAULT false,
    "ErrorMessage" varchar(500),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "UserMemory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" varchar(100) NOT NULL UNIQUE,
    "FavoriteModules" text,
    "FrequentTopics" text,
    "RecentQuestions" text,
    "ExpertiseLevel" varchar(20) NOT NULL DEFAULT 'Beginner',
    "PreferredLanguage" varchar(5) NOT NULL DEFAULT 'id',
    "DetectedDepartment" varchar(100),
    "DetectedRole" varchar(100),
    "TotalSessions" integer NOT NULL DEFAULT 0,
    "TotalQuestions" integer NOT NULL DEFAULT 0,
    "HowToCount" integer NOT NULL DEFAULT 0,
    "TroubleshootingCount" integer NOT NULL DEFAULT 0,
    "AverageConfidenceReceived" double precision NOT NULL DEFAULT 0,
    "FirstSeenAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "LastSeenAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "LastSessionId" varchar(100),
    "LastSessionAt" timestamp with time zone
);

CREATE TABLE IF NOT EXISTS "LearningCandidates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SourceChatHistoryId" integer,
    "QuestionHash" varchar(64) NOT NULL,
    "OriginalQuestion" text NOT NULL,
    "OriginalAnswer" text NOT NULL,
    "EditedQuestion" text NOT NULL DEFAULT '',
    "EditedAnswer" text NOT NULL DEFAULT '',
    "Status" varchar(80) NOT NULL DEFAULT 'NeedsEdit',
    "Category" varchar(100) NOT NULL DEFAULT 'AI Learning',
    "Tags" varchar(500) NOT NULL DEFAULT 'ai-learning,approved,reviewed',
    "Source" varchar(200) NOT NULL DEFAULT '',
    "SourceDocumentIds" text NOT NULL DEFAULT '',
    "ConfidenceScore" double precision,
    "QualityScore" double precision,
    "CandidateReason" varchar(1000) NOT NULL DEFAULT '',
    "Flags" varchar(1000) NOT NULL DEFAULT '',
    "ContainsSensitiveData" boolean NOT NULL DEFAULT false,
    "SensitiveReason" varchar(500) NOT NULL DEFAULT '',
    "Frequency" integer NOT NULL DEFAULT 1,
    "LastSeenAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ReviewNotes" text NOT NULL DEFAULT '',
    "ReviewedBy" varchar(100) NOT NULL DEFAULT '',
    "ReviewedAt" timestamp with time zone,
    "PublishedDocumentId" integer,
    "PublishedAt" timestamp with time zone,
    "PublishedBy" varchar(100) NOT NULL DEFAULT '',
    "PublishError" text NOT NULL DEFAULT '',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "LearningCandidateAuditLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CandidateId" integer NOT NULL,
    "Action" varchar(80) NOT NULL DEFAULT '',
    "Actor" varchar(100) NOT NULL DEFAULT '',
    "OldStatus" varchar(80) NOT NULL DEFAULT '',
    "NewStatus" varchar(80) NOT NULL DEFAULT '',
    "Notes" text NOT NULL DEFAULT '',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "KnowledgeBaseChunks"
ADD COLUMN IF NOT EXISTS "EmbeddingVector" vector(2560);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_KnowledgeBaseChunks_KnowledgeBaseDocuments_DocumentId'
    ) THEN
        ALTER TABLE "KnowledgeBaseChunks"
        ADD CONSTRAINT "FK_KnowledgeBaseChunks_KnowledgeBaseDocuments_DocumentId"
        FOREIGN KEY ("DocumentId") REFERENCES "KnowledgeBaseDocuments"("Id") ON DELETE CASCADE;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_KBDocuments_Category" ON "KnowledgeBaseDocuments" ("Category");
CREATE INDEX IF NOT EXISTS "IX_KBDocuments_IsActive" ON "KnowledgeBaseDocuments" ("IsActive");
CREATE INDEX IF NOT EXISTS "IX_KBDocuments_CreatedAt" ON "KnowledgeBaseDocuments" ("CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_KBChunks_DocumentId" ON "KnowledgeBaseChunks" ("DocumentId");
CREATE INDEX IF NOT EXISTS "IX_KBChunks_ChunkIndex" ON "KnowledgeBaseChunks" ("ChunkIndex");
CREATE INDEX IF NOT EXISTS "IX_ChatHistory_SessionId" ON "ChatHistory" ("SessionId");
CREATE INDEX IF NOT EXISTS "IX_ChatHistory_UserId" ON "ChatHistory" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AiUsageLog_CreatedAt" ON "AiUsageLogs" ("CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_AiUsageLog_UserId" ON "AiUsageLogs" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AiUsageLog_Model" ON "AiUsageLogs" ("Model");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserMemory_UserId" ON "UserMemory" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_LearningCandidates_QuestionHash" ON "LearningCandidates" ("QuestionHash");
CREATE INDEX IF NOT EXISTS "IX_LearningCandidates_Status_UpdatedAt" ON "LearningCandidates" ("Status", "UpdatedAt");
CREATE INDEX IF NOT EXISTS "IX_LearningCandidates_SourceChatHistoryId" ON "LearningCandidates" ("SourceChatHistoryId");
CREATE INDEX IF NOT EXISTS "IX_LearningCandidateAuditLogs_CandidateId_CreatedAt" ON "LearningCandidateAuditLogs" ("CandidateId", "CreatedAt");
